// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * A CancelFunc tells an operation to abandon its work.
 * A CancelFunc does not wait for the work to stop.
 * A CancelFunc may be called by multiple goroutines simultaneously.
 * After the first call, subsequent calls to a CancelFunc do nothing.
 */
export type CancelFunc = any;
