// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../encoding/json/models.js";

/**
 * Envelope is the wire message. It is the only cross-language contract
 * alongside the JSON schemas in packages/proto. Unknown fields are ignored
 * on decode; encoders MUST NOT rely on extra fields being read.
 */
export interface Envelope {
    "protocol_v": number;
    "type": string;
    "sender": SenderInfo;
    "capabilities": string[] | null;
    "payload"?: json$0.RawMessage;
}

/**
 * SenderInfo identifies the sender of an envelope. AppVersion is the
 * human-readable version (e.g. "0.1.0"), display-only and optional for
 * backward compatibility: older peers omit it and gate purely on builds.
 */
export interface SenderInfo {
    "platform": string;
    "app_build": number;
    "min_peer_build": number;
    "app_version"?: string;
}

/**
 * WSConn wraps a coder/websocket connection with thread-safe envelope writing
 * and peer metadata for real-time bi-directional streaming.
 */
export interface WSConn {
}
