// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppSettings is the Mac's app settings: clipboard sync direction plus the
 * notification master switch. UpdatedUnix/UpdatedBy implement
 * last-writer-wins against the phone's blob (ties go to mac). Persisted in
 * settings.json so a restart keeps the last choice.
 */
export interface AppSettings {
    "clipboard_mode": string;
    "notifications_enabled": boolean;
    "updated_unix": number;
    "updated_by": string;
}

/**
 * ClipNotice is the typed clipboard state for the frontend. Text is the
 * full current value (UI truncates for preview); ChangedUnix orders pushes;
 * Origin is "mac" or "android". HasText is false when no copy exists yet.
 * Clipboard bodies never reach the log (lengths only).
 */
export interface ClipNotice {
    "HasText": boolean;
    "Text": string;
    "ChangedUnix": number;
    "Origin": string;
    "Preview": string;
    "Pending": boolean;
}

/**
 * LastDeviceNotice is the typed last-phone state for the frontend: the
 * offline "Last connected" card. Empty when no phone ever paired.
 * DeviceName/Model/BatteryPct/Charging are the phone's latest advertised
 * facts (nil battery fields = unknown, never 0% by default). CustomName is
 * the Mac-local rename alias; DisplayName is what the UI shows
 * (custom alias, else advertised name, else "" and the UI falls back to
 * "Phone" so older frontends keep working).
 */
export interface LastDeviceNotice {
    "HasDevice": boolean;
    "Host": string;
    "Port": number;
    "Addr": string;
    "LastSeenUnix": number;
    "DeviceName": string;
    "Model": string;
    "BatteryPct": number | null;
    "Charging": boolean | null;
    "BatteryUnix": number;
    "CustomName": string;
    "DisplayName": string;
}

/**
 * NotifList is the typed notification mirror for the frontend: rows plus
 * the unseen badge count. A struct (not a tuple) so the Wails binding
 * carries both halves in one JSON object.
 */
export interface NotifList {
    "Items": NotifView[] | null;
    "Unseen": number;
}

/**
 * NotifView is the frontend row for one mirrored notification.
 */
export interface NotifView {
    "id": string;
    "app": string;
    "title": string;
    "text": string;
    "posted_unix": number;
}

/**
 * UpdateNotice is the typed version-gate state for the frontend: the single
 * source of truth, so UI never scrapes log text. Message stays verbatim
 * (canonical core text, never paraphrased). RequiredVersion/CurrentVersion
 * are display-only and may be "" from older peers; RequiredBuild gates.
 */
export interface UpdateNotice {
    "Active": boolean;
    "Self": boolean;
    "Message": string;
    "RequiredVersion": string;
    "CurrentVersion": string;
    "RequiredBuild": number;
}
