// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppSettings is the Mac's app settings: notification master switch + clipboard mode.
 * UpdatedUnix/UpdatedBy implement last-writer-wins against the phone's blob
 * (ties go to mac). Persisted in settings.json so a restart keeps the last choice.
 */
export interface AppSettings {
    "notifications_enabled": boolean;
    "clipboard_mode": string;
    "updated_unix": number;
    "updated_by": string;
}

/**
 * ClipNotice is the typed clipboard state for the frontend. For text, Text
 * holds the full value (UI truncates for preview); for images, ImageB64+Mmime
 * hold the base64 payload. Kind is "text" or "image". ImageB64 is never
 * logged verbatim; handlers log lengths and IDs only. Filename is sanitized
 * basename for UTI/extension preservation.
 */
export interface ClipNotice {
    "HasText": boolean;
    "Kind": string;
    "Text": string;
    "Mime": string;
    "ImageB64": string;
    "Filename": string;
    "ChangedUnix": number;
    "Origin": string;
    "Preview": string;
    "Pending": boolean;
}

/**
 * FileEntryView is the Wails-bound row for one file. Mirrors core.FileEntry
 * but json-tagged for TS bindings.
 */
export interface FileEntryView {
    "name": string;
    "path": string;
    "is_dir": boolean;
    "size": number;
    "mod_time": number;
    "mime"?: string;
}

/**
 * FileListResult is the typed listing for the frontend. Error is "" on success.
 * ErrorCode/Permission are machine-readable (permission_denied + files) so
 * the UI renders per-viewer empty states without string matching.
 */
export interface FileListResult {
    "path": string;
    "entries": FileEntryView[] | null;
    "error"?: string;
    "error_code"?: string;
    "permission"?: string;
}

/**
 * FileTransferView is the Wails-bound progress row.
 */
export interface FileTransferView {
    "id": string;
    "path": string;

    /**
     * upload | download
     */
    "direction": string;

    /**
     * running | done | error | cancelled
     */
    "status": string;

    /**
     * 0..100
     */
    "progress": number;
    "total_size": number;
    "done_size": number;
    "error"?: string;
}

/**
 * LastDeviceNotice is the typed last-phone state for the frontend: the
 * offline "Last connected" card. Empty when no phone ever paired.
 * DeviceName/Model/BatteryPct/Charging are the phone's latest advertised
 * facts (nil battery fields = unknown, never 0% by default). CustomName is
 * the Mac-local rename alias; DisplayName is what the UI shows
 * (custom alias, else advertised name, else "" and the UI falls back to
 * "Phone" so older frontends keep working).
 */
export interface LastDeviceNotice {
    "HasDevice": boolean;
    "Host": string;
    "Port": number;
    "Addr": string;
    "LastSeenUnix": number;
    "DeviceName": string;
    "Model": string;
    "BatteryPct": number | null;
    "Charging": boolean | null;
    "BatteryUnix": number;
    "CustomName": string;
    "DisplayName": string;
    "FilesPermission": string;
    "PhotosPermission": string;
}

/**
 * NotifList is the typed notification mirror for the frontend: rows plus
 * the unseen badge count. A struct (not a tuple) so the Wails binding
 * carries both halves in one JSON object.
 */
export interface NotifList {
    "Items": NotifView[] | null;
    "Unseen": number;
}

/**
 * NotifView is the frontend row for one mirrored notification. PackageName
 * and IconB64 are additive 0.3.0+ (may be "" from older phones). IconB64 is
 * base64 PNG ~96px, cached per package, never logged.
 */
export interface NotifView {
    "id": string;
    "app": string;
    "package_name": string;
    "app_icon_b64": string;
    "group_key": string;
    "title": string;
    "text": string;
    "posted_unix": number;
}

/**
 * PhotoDeleteItemView is per-item delete outcome.
 */
export interface PhotoDeleteItemView {
    "photo_id": string;
    "ok": boolean;
    "error"?: string;
    "error_code"?: string;
}

/**
 * PhotoDeleteResult is the typed batch delete outcome.
 */
export interface PhotoDeleteResult {
    "results": PhotoDeleteItemView[] | null;
    "error"?: string;
    "error_code"?: string;
    "permission"?: string;
}

/**
 * PhotoEntryView is the Wails-bound row for one photo.
 */
export interface PhotoEntryView {
    "photo_id": string;
    "taken_at": number;
    "width"?: number;
    "height"?: number;
    "mime"?: string;
    "size"?: number;
    "orientation"?: number;
}

/**
 * PhotoListResult is the typed paged listing for the frontend.
 */
export interface PhotoListResult {
    "entries": PhotoEntryView[] | null;
    "next_cursor"?: string;
    "error"?: string;
    "error_code"?: string;
    "permission"?: string;
}

/**
 * PhotoThumbResult is one fetched thumbnail.
 */
export interface PhotoThumbResult {
    "photo_id": string;
    "mime"?: string;
    "data_b64"?: string;
    "error"?: string;
}

/**
 * PhotoTransferView is the Wails-bound progress row for photo downloads.
 */
export interface PhotoTransferView {
    "id": string;
    "photo_id": string;
    "status": string;
    "progress": number;
    "total_size": number;
    "done_size": number;
    "error"?: string;
}

/**
 * UpdateNotice is the typed version-gate state for the frontend: the single
 * source of truth, so UI never scrapes log text. Message stays verbatim
 * (canonical core text, never paraphrased). RequiredVersion/CurrentVersion
 * are display-only and may be "" from older peers; RequiredBuild gates.
 */
export interface UpdateNotice {
    "Active": boolean;
    "Self": boolean;
    "Message": string;
    "RequiredVersion": string;
    "CurrentVersion": string;
    "RequiredBuild": number;
}
