// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LastDeviceNotice is the typed last-phone state for the frontend: the
 * offline "Last connected" card. Empty when no phone ever paired.
 */
export interface LastDeviceNotice {
    "HasDevice": boolean;
    "Host": string;
    "Port": number;
    "Addr": string;
    "LastSeenUnix": number;
}

/**
 * UpdateNotice is the typed version-gate state for the frontend: the single
 * source of truth, so UI never scrapes log text. Message stays verbatim
 * (canonical core text, never paraphrased).
 */
export interface UpdateNotice {
    "Active": boolean;
    "Self": boolean;
    "Message": string;
}
