// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service exposes pair state and phone-ping actions to the Wails frontend.
 * Pair fields are set once at startup by main.go; peer coordinates are
 * learned later from accepted phone pings (see WrapHandler) and remembered
 * on disk (see persist.go) so a restart still shows the last phone.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../../core/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelPhotoTransfer marks a photo download cancelled.
 */
export function CancelPhotoTransfer(id: string): $CancellablePromise<void> {
    return $Call.ByID(2014360541, id);
}

/**
 * CancelTransfer marks a transfer cancelled (best-effort, no wire cancel yet).
 */
export function CancelTransfer(id: string): $CancellablePromise<string> {
    return $Call.ByID(1201368133, id);
}

/**
 * ClearNotifications empties the mirror locally. The phone reposts live
 * notifications on its next heartbeat.
 */
export function ClearNotifications(): $CancellablePromise<string> {
    return $Call.ByID(1935873051);
}

/**
 * ConfigurePairing stashes the QR rebuild inputs. Called once by main.go;
 * tests that never rotate can skip it (rotation fails closed without it).
 * Scalar args only so the Wails binding stays JSON-representable;
 * pubkeyBase64 is the base64 identity public key from the pair payload.
 */
export function ConfigurePairing(deviceName: string, platform: string, host: string, port: number, fingerprint: string, pubkeyBase64: string): $CancellablePromise<void> {
    return $Call.ByID(3563679260, deviceName, platform, host, port, fingerprint, pubkeyBase64);
}

/**
 * DeletePhone deletes a file or empty directory on the phone.
 */
export function DeletePhone(path: string): $CancellablePromise<string> {
    return $Call.ByID(2020732645, path);
}

/**
 * DeletePhonePhotos deletes a batch and waits for photo-delete-resp.
 */
export function DeletePhonePhotos(photoIDs: string[] | null): $CancellablePromise<$models.PhotoDeleteResult> {
    return $Call.ByID(2829798832, photoIDs);
}

/**
 * DismissNotification drops one notification locally and syncs the dismissal
 * to the phone when paired (queued otherwise).
 */
export function DismissNotification(id: string): $CancellablePromise<string> {
    return $Call.ByID(132836199, id);
}

/**
 * DownloadFileToExactPath downloads a phone file directly into exactDestPath on the Mac.
 * Used by native drag-out (NSFilePromiseProvider) so Finder receives the file directly
 * in the dropped directory (e.g. external drives or custom folders).
 */
export function DownloadFileToExactPath(remotePath: string, exactDestPath: string): $CancellablePromise<void> {
    return $Call.ByID(3529188141, remotePath, exactDestPath);
}

/**
 * ForgetLastDevice drops the remembered phone: it clears the ephemeral
 * return path, the TOFU phone pin, and the persisted device.json so the UI
 * falls back to the pairing flow. It then rotates the pair token (persisted
 * + live server + rebuilt QR) so the forgotten phone's stored token stops
 * verifying: its next ping gets 403 and it unpairs itself with a "scan the
 * new code" notice instead of silently re-capturing the peer. Fail closed
 * when no phone was ever remembered; a disk-delete failure still clears
 * memory but returns the wrapped error. A rotation failure also returns an
 * error (peer state is still cleared, but the old QR stays valid).
 */
export function ForgetLastDevice(): $CancellablePromise<string> {
    return $Call.ByID(1960282719);
}

/**
 * GetAppVersion returns this Mac build's human version (0.1.0 launch).
 * Typed binding for the footer/About row; mirrors core.CurrentAppVersion.
 */
export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(1818523565);
}

/**
 * GetClipboard returns the synced clipboard state for the Clipboard pane.
 */
export function GetClipboard(): $CancellablePromise<$models.ClipNotice> {
    return $Call.ByID(1750367318);
}

/**
 * GetFingerprint returns the hex SHA-256 of the server TLS cert (TOFU pin).
 */
export function GetFingerprint(): $CancellablePromise<string> {
    return $Call.ByID(1850633148);
}

/**
 * GetLastDevice returns the last phone this Mac paired with, even after the
 * ephemeral peer expired or the app restarted. Typed binding for the offline
 * "Last connected" card; HasDevice is false when no phone ever paired.
 * Battery fields are nil while unknown; DisplayName is the rename alias when
 * set, else the advertised name, else "" (the UI falls back to "Phone").
 */
export function GetLastDevice(): $CancellablePromise<$models.LastDeviceNotice> {
    return $Call.ByID(2294029394);
}

/**
 * GetLastFileList returns the last successful listing (poll fallback).
 */
export function GetLastFileList(): $CancellablePromise<$models.FileListResult> {
    return $Call.ByID(3649083418);
}

/**
 * GetLog returns recent core server log lines, oldest first.
 */
export function GetLog(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2517628202);
}

/**
 * GetNotifications returns mirrored notifications (newest first) plus the
 * unseen badge count. Opening the pane should call MarkNotificationsSeen.
 */
export function GetNotifications(): $CancellablePromise<$models.NotifList> {
    return $Call.ByID(985061532);
}

/**
 * GetPairJSON returns the EncodePairQR JSON shown as the pairing QR.
 */
export function GetPairJSON(): $CancellablePromise<string> {
    return $Call.ByID(1076374734);
}

/**
 * GetPeerAddr returns "host:port" learned from the phone's last accepted
 * ping, or "" while unknown or expired (past peerTTL). The frontend keeps
 * [Ping phone] disabled until this is non-empty.
 */
export function GetPeerAddr(): $CancellablePromise<string> {
    return $Call.ByID(1816887919);
}

/**
 * GetPeerDevice returns the live advertised facts while the phone is paired
 * (within peerTTL), or null-equivalent (HasDevice false) otherwise. Typed
 * binding so the sidebar header shows model + battery without scraping logs.
 */
export function GetPeerDevice(): $CancellablePromise<$models.LastDeviceNotice> {
    return $Call.ByID(3047827702);
}

/**
 * GetPhotoStreamURL reissues the loopback URL for a live stream transfer.
 */
export function GetPhotoStreamURL(transferID: string): $CancellablePromise<string> {
    return $Call.ByID(3257170749, transferID);
}

/**
 * GetPhotoTransfers returns photo download progress rows.
 */
export function GetPhotoTransfers(): $CancellablePromise<$models.PhotoTransferView[] | null> {
    return $Call.ByID(1977239172);
}

/**
 * GetSettings returns the current app settings for the Settings pane.
 */
export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(2309659813);
}

/**
 * GetTransfers returns snapshot of active/recent transfers for the UI.
 * Completed/errored transfers older than 5 seconds are pruned automatically.
 */
export function GetTransfers(): $CancellablePromise<$models.FileTransferView[] | null> {
    return $Call.ByID(1581331400);
}

/**
 * GetUpdateNotice returns the newest version-gate outcome, or inactive.
 * Typed binding: the frontend banners this verbatim, never parses GetLog.
 */
export function GetUpdateNotice(): $CancellablePromise<$models.UpdateNotice> {
    return $Call.ByID(2756057269);
}

/**
 * IsPaired reports whether an accepted phone ping taught us the return path
 * recently (within peerTTL). Typed binding: the frontend derives `paired`
 * from this, never from log text. It flips false peerTTL after the last
 * accepted ping, or immediately after a dial failure clears the peer.
 */
export function IsPaired(): $CancellablePromise<boolean> {
    return $Call.ByID(1285126505);
}

/**
 * ListPhoneFiles requests a directory listing from the phone and waits for
 * the file-list-resp push. It returns the listing or an error after 8s.
 * Path is sandboxed rel path ("" = root).
 */
export function ListPhoneFiles(path: string): $CancellablePromise<$models.FileListResult> {
    return $Call.ByID(3430699727, path);
}

/**
 * ListPhonePhotos requests one paged listing and waits for photo-list-resp.
 */
export function ListPhonePhotos(cursor: string, limit: number): $CancellablePromise<$models.PhotoListResult> {
    return $Call.ByID(3114372837, cursor, limit);
}

/**
 * MarkNotificationsSeen resets the badge count.
 */
export function MarkNotificationsSeen(): $CancellablePromise<void> {
    return $Call.ByID(175582900);
}

/**
 * MkdirPhone creates a directory on the phone.
 */
export function MkdirPhone(path: string): $CancellablePromise<string> {
    return $Call.ByID(4008516317, path);
}

/**
 * OnWSConnect is called immediately when an authenticated phone establishes
 * a persistent TLS WebSocket connection. Flips IsPaired true and notifies the UI.
 */
export function OnWSConnect(conn: core$0.WSConn | null, remoteAddr: string): $CancellablePromise<void> {
    return $Call.ByID(1486794675, conn, remoteAddr);
}

/**
 * OnWSDisconnect is called immediately when the phone disconnects (e.g. app closed,
 * Wi-Fi lost, socket EOF). Flips IsPaired false with zero polling delay.
 */
export function OnWSDisconnect(conn: core$0.WSConn | null): $CancellablePromise<void> {
    return $Call.ByID(319628405, conn);
}

/**
 * OnWSEnvelope handles real-time inbound wire envelopes over the persistent WebSocket.
 */
export function OnWSEnvelope(conn: core$0.WSConn | null, env: core$0.Envelope): $CancellablePromise<void> {
    return $Call.ByID(4145464947, conn, env);
}

/**
 * PickDownloadDir is a placeholder for native folder picker. Wails v3 dialog is invoked from frontend via window API;
 * backend keeps this for compat and simply returns empty meaning "use Downloads".
 */
export function PickDownloadDir(): $CancellablePromise<string> {
    return $Call.ByID(2204431912);
}

/**
 * PrepareDownloadForDrag returns an existing staged path if already downloaded.
 * It no longer triggers unprompted background downloads into ~/Downloads.
 */
export function PrepareDownloadForDrag(remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(3148293680, remotePath);
}

/**
 * PushClipboard records a Mac-side text copy and sends it immediately to the
 * phone (manual Send only). Kept for typed draft fallback; prefer PushClipboardCurrent.
 */
export function PushClipboard(text: string): $CancellablePromise<string> {
    return $Call.ByID(4028054998, text);
}

/**
 * PushClipboardCurrent sends whatever is currently on the system pasteboard
 * (image preferred, else text). Images are normalized to PNG on send
 * (TIFF/HEIC/HEIF → PNG via sips/stdlib, over-cap PNG → JPEG q85) so the
 * phone receives a universally renderable format. This is the single "Send
 * clipboard" action.
 */
export function PushClipboardCurrent(): $CancellablePromise<string> {
    return $Call.ByID(482963119);
}

/**
 * PushClipboardImage records a Mac-side image and sends it immediately.
 * b64 must be base64-encoded image, mime whitelisted. Fail-closed on oversize.
 */
export function PushClipboardImage(b64: string, mime: string): $CancellablePromise<string> {
    return $Call.ByID(1427201659, b64, mime);
}

/**
 * ReconnectToLastDevice redials the remembered phone even after the
 * ephemeral peer expired or the app restarted. It tries the last host first,
 * then remembered candidate IPs (DHCP changes), so a next-day / new-WiFi
 * reconnect heals without a fresh QR scan. Success refreshes the peer
 * (IsPaired flips true); dial failures keep the remembered device so the UI
 * still shows "Last connected". Fail closed when no phone ever paired.
 */
export function ReconnectToLastDevice(): $CancellablePromise<string> {
    return $Call.ByID(1244154842);
}

/**
 * RenamePhone renames a file or directory on the phone within the same directory.
 */
export function RenamePhone($from: string, to: string): $CancellablePromise<string> {
    return $Call.ByID(3193722462, $from, to);
}

/**
 * RequestPhoneFile asks the phone to send a file back chunk-by-chunk.
 * downloadDir is a local Mac directory (absolute) to save into; if empty,
 * uses system Downloads. Returns transfer id for progress polling.
 */
export function RequestPhoneFile(remotePath: string, downloadDir: string): $CancellablePromise<string> {
    return $Call.ByID(3843937649, remotePath, downloadDir);
}

/**
 * RequestPhoneMedia starts a full-res download with an explicit mime hint
 * for the file extension. The frontend passes the listing entry mime.
 */
export function RequestPhoneMedia(photoID: string, mime: string, downloadDir: string): $CancellablePromise<string> {
    return $Call.ByID(4097460865, photoID, mime, downloadDir);
}

/**
 * RequestPhonePhoto starts a full-res download; progress via GetPhotoTransfers.
 * Legacy wrapper: no mime hint, so images keep .jpg and videos fall back
 * to .bin. New callers prefer RequestPhoneMedia.
 */
export function RequestPhonePhoto(photoID: string, downloadDir: string): $CancellablePromise<string> {
    return $Call.ByID(3958777001, photoID, downloadDir);
}

/**
 * RequestPhotoRange pulls a byte range for video streaming without
 * finalizing: chunks accumulate in a sparse part file and progress flows
 * via GetPhotoTransfers / photo-transfers:changed. Length 0 is rejected
 * here (use RequestPhoneMedia for full downloads). Range pulls require a
 * build-8 peer; older phones get UPDATE_REQUIRED instead of a timeout.
 */
export function RequestPhotoRange(photoID: string, mime: string, offset: number, length: number): $CancellablePromise<string> {
    return $Call.ByID(1255832072, photoID, mime, offset, length);
}

/**
 * RequestPhotoThumb fetches one thumbnail and waits for photo-thumb-resp.
 * Checks the in-memory LRU cache first (RAM-only, zero SSD wear).
 */
export function RequestPhotoThumb(photoID: string, thumbSize: number): $CancellablePromise<$models.PhotoThumbResult> {
    return $Call.ByID(2665987689, photoID, thumbSize);
}

/**
 * RevealInFinder opens the staging dir in Finder (fallback for drag-out).
 */
export function RevealInFinder(transferID: string): $CancellablePromise<string> {
    return $Call.ByID(3930839894, transferID);
}

/**
 * SendPingToPhone pings the phone's listener at the captured peer address
 * using core.SendPing and the pair token. It returns a short RTT summary;
 * the RTT is also appended to the log. An update-required reply is logged
 * with the parseable prefix (verbatim canonical message) and returned as an
 * error so the UI can banner immediately; an auth rejection is logged and
 * returned with the peer kept. Any other (dial/network) failure clears the
 * ephemeral peer (the remembered device stays) and logs
 * "phone peer lost (<err>)" so IsPaired flips false on the next poll.
 * Fail closed while peer coordinates are unknown.
 */
export function SendPingToPhone(): $CancellablePromise<string> {
    return $Call.ByID(2215868813);
}

/**
 * SetClipboardMode flips the clipboard auto direction, persists, and syncs
 * when paired. Modes: both, android_to_mac, mac_to_android, disabled.
 */
export function SetClipboardMode(mode: string): $CancellablePromise<string> {
    return $Call.ByID(1377316233, mode);
}

/**
 * SetCustomName stores the Mac-local rename alias shown instead of the
 * phone's advertised name. Empty clears the alias (falls back to the
 * advertised name). Over-long input fails closed without touching state.
 * The alias lives in device.json keyed to this phone; advertised facts keep
 * updating underneath so clearing reveals the current phone name.
 */
export function SetCustomName(name: string): $CancellablePromise<string> {
    return $Call.ByID(4188241244, name);
}

/**
 * SetNotificationsEnabled flips the notification master switch, persists,
 * and syncs when paired.
 */
export function SetNotificationsEnabled(enabled: boolean): $CancellablePromise<string> {
    return $Call.ByID(2764020233, enabled);
}

/**
 * StartClipboardWatcher launches the auto clipboard poller; idempotent.
 */
export function StartClipboardWatcher(): $CancellablePromise<void> {
    return $Call.ByID(2972424142);
}

/**
 * StartFileDrag initiates a native macOS dragging session using NSFilePromiseProvider.
 * Finder requests and downloads the file directly to the dropped folder URL on demand.
 */
export function StartFileDrag(remotePath: string, filename: string, size: number): $CancellablePromise<boolean> {
    return $Call.ByID(2292223408, remotePath, filename, size);
}

/**
 * StartPhotoStream opens a video stream: creates a range transfer, fires a
 * prefix pull for fast first frame, and returns the transfer ID plus the
 * loopback URL for the frontend <video> element. Build-8 peer required.
 */
export function StartPhotoStream(photoID: string, mime: string): $CancellablePromise<$models.PhotoStreamStart> {
    return $Call.ByID(1386289308, photoID, mime);
}

/**
 * StopClipboardWatcher halts the auto clipboard poller.
 */
export function StopClipboardWatcher(): $CancellablePromise<void> {
    return $Call.ByID(2953174018);
}

/**
 * UploadBrowserFile uploads a single file supplied as base64 from the browser
 * (drag-n-drop fallback when Finder paths are not available). It chunks the
 * decoded bytes exactly like UploadLocalFiles.
 */
export function UploadBrowserFile(b64: string, filename: string, remoteDir: string): $CancellablePromise<string> {
    return $Call.ByID(1938008777, b64, filename, remoteDir);
}

/**
 * UploadBrowserFileWithRelPath uploads a file with relative path (for folder drag via webkitRelativePath).
 */
export function UploadBrowserFileWithRelPath(b64: string, relPath: string, remoteDir: string): $CancellablePromise<string> {
    return $Call.ByID(2237756107, b64, relPath, remoteDir);
}

/**
 * UploadLocalFiles uploads one or more local Mac files and folders into remoteDir on the phone.
 * Each localPath may be a file or directory; directories are walked recursively.
 * Drag-n-drop calls this with the dropped file paths.
 */
export function UploadLocalFiles(localPaths: string[] | null, remoteDir: string): $CancellablePromise<string> {
    return $Call.ByID(2928882063, localPaths, remoteDir);
}

/**
 * WriteActiveWS attempts to send an envelope directly over the active WebSocket.
 * Returns true if sent, false if no active WebSocket is connected or write failed.
 */
export function WriteActiveWS(env: core$0.Envelope): $CancellablePromise<boolean> {
    return $Call.ByID(3336139279, env);
}
