// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service exposes pair state and phone-ping actions to the Wails frontend.
 * Pair fields are set once at startup by main.go; peer coordinates are
 * learned later from accepted phone pings (see WrapHandler) and remembered
 * on disk (see persist.go) so a restart still shows the last phone.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as context$0 from "../../../context/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearNotifications empties the mirror locally. The phone reposts live
 * notifications on its next heartbeat.
 */
export function ClearNotifications(): $CancellablePromise<string> {
    return $Call.ByID(1935873051);
}

/**
 * ConfigurePairing stashes the QR rebuild inputs. Called once by main.go;
 * tests that never rotate can skip it (rotation fails closed without it).
 * Scalar args only so the Wails binding stays JSON-representable;
 * pubkeyBase64 is the base64 identity public key from the pair payload.
 */
export function ConfigurePairing(deviceName: string, platform: string, host: string, port: number, fingerprint: string, pubkeyBase64: string): $CancellablePromise<void> {
    return $Call.ByID(3563679260, deviceName, platform, host, port, fingerprint, pubkeyBase64);
}

/**
 * DismissNotification drops one notification locally and syncs the dismissal
 * to the phone when paired (queued otherwise).
 */
export function DismissNotification(id: string): $CancellablePromise<string> {
    return $Call.ByID(132836199, id);
}

/**
 * ForgetLastDevice drops the remembered phone: it clears the ephemeral
 * return path, the TOFU phone pin, and the persisted device.json so the UI
 * falls back to the pairing flow. It then rotates the pair token (persisted
 * + live server + rebuilt QR) so the forgotten phone's stored token stops
 * verifying: its next ping gets 403 and it unpairs itself with a "scan the
 * new code" notice instead of silently re-capturing the peer. Fail closed
 * when no phone was ever remembered; a disk-delete failure still clears
 * memory but returns the wrapped error. A rotation failure also returns an
 * error (peer state is still cleared, but the old QR stays valid).
 */
export function ForgetLastDevice(): $CancellablePromise<string> {
    return $Call.ByID(1960282719);
}

/**
 * GetAppVersion returns this Mac build's human version (0.1.0 launch).
 * Typed binding for the footer/About row; mirrors core.CurrentAppVersion.
 */
export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(1818523565);
}

/**
 * GetClipboard returns the synced clipboard state for the Clipboard pane.
 */
export function GetClipboard(): $CancellablePromise<$models.ClipNotice> {
    return $Call.ByID(1750367318);
}

/**
 * GetFingerprint returns the hex SHA-256 of the server TLS cert (TOFU pin).
 */
export function GetFingerprint(): $CancellablePromise<string> {
    return $Call.ByID(1850633148);
}

/**
 * GetLastDevice returns the last phone this Mac paired with, even after the
 * ephemeral peer expired or the app restarted. Typed binding for the offline
 * "Last connected" card; HasDevice is false when no phone ever paired.
 * Battery fields are nil while unknown; DisplayName is the rename alias when
 * set, else the advertised name, else "" (the UI falls back to "Phone").
 */
export function GetLastDevice(): $CancellablePromise<$models.LastDeviceNotice> {
    return $Call.ByID(2294029394);
}

/**
 * GetLog returns recent core server log lines, oldest first.
 */
export function GetLog(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2517628202);
}

/**
 * GetNotifications returns mirrored notifications (newest first) plus the
 * unseen badge count. Opening the pane should call MarkNotificationsSeen.
 */
export function GetNotifications(): $CancellablePromise<$models.NotifList> {
    return $Call.ByID(985061532);
}

/**
 * GetPairJSON returns the EncodePairQR JSON shown as the pairing QR.
 */
export function GetPairJSON(): $CancellablePromise<string> {
    return $Call.ByID(1076374734);
}

/**
 * GetPeerAddr returns "host:port" learned from the phone's last accepted
 * ping, or "" while unknown or expired (past peerTTL). The frontend keeps
 * [Ping phone] disabled until this is non-empty.
 */
export function GetPeerAddr(): $CancellablePromise<string> {
    return $Call.ByID(1816887919);
}

/**
 * GetPeerDevice returns the live advertised facts while the phone is paired
 * (within peerTTL), or null-equivalent (HasDevice false) otherwise. Typed
 * binding so the sidebar header shows model + battery without scraping logs.
 */
export function GetPeerDevice(): $CancellablePromise<$models.LastDeviceNotice> {
    return $Call.ByID(3047827702);
}

/**
 * GetSettings returns the current app settings for the Settings pane.
 * Typed binding; never scrapes the log.
 */
export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(2309659813);
}

/**
 * GetUpdateNotice returns the newest version-gate outcome, or inactive.
 * Typed binding: the frontend banners this verbatim, never parses GetLog.
 */
export function GetUpdateNotice(): $CancellablePromise<$models.UpdateNotice> {
    return $Call.ByID(2756057269);
}

/**
 * HeartbeatTick is the 20s auto-reconnect tick (mirrors the Android
 * heartbeat): when paired it refreshes presence with a ping; when expired it
 * redials the remembered phone. Queued feature syncs (settings, clipboard,
 * notification dismissals) flush after presence. Failures only land in the
 * log — never an error return, never the update banner path beyond setUpdate.
 */
export function HeartbeatTick(): $CancellablePromise<void> {
    return $Call.ByID(3546295225);
}

/**
 * IsPaired reports whether an accepted phone ping taught us the return path
 * recently (within peerTTL). Typed binding: the frontend derives `paired`
 * from this, never from log text. It flips false peerTTL after the last
 * accepted ping, or immediately after a dial failure clears the peer.
 */
export function IsPaired(): $CancellablePromise<boolean> {
    return $Call.ByID(1285126505);
}

/**
 * MarkNotificationsSeen resets the badge count.
 */
export function MarkNotificationsSeen(): $CancellablePromise<void> {
    return $Call.ByID(175582900);
}

/**
 * PushClipboard records a Mac-side copy and syncs it when the mode allows
 * outbound flow (mac_to_phone or two_way). Inbound-blocked modes still store
 * locally; the text sends on the next mode change that allows it.
 */
export function PushClipboard(text: string): $CancellablePromise<string> {
    return $Call.ByID(4028054998, text);
}

/**
 * ReconnectToLastDevice redials the remembered phone even after the
 * ephemeral peer expired or the app restarted. It tries the last host first,
 * then remembered candidate IPs (DHCP changes), so a next-day / new-WiFi
 * reconnect heals without a fresh QR scan. Success refreshes the peer
 * (IsPaired flips true); dial failures keep the remembered device so the UI
 * still shows "Last connected". Fail closed when no phone ever paired.
 */
export function ReconnectToLastDevice(): $CancellablePromise<string> {
    return $Call.ByID(1244154842);
}

/**
 * RequestPhoneClipboard asks the phone for its latest clipboard (clip-request
 * pull). The phone answers with a clip-push on its next flush; the reply
 * lands in ingestClipBody. Fail closed while unpaired.
 */
export function RequestPhoneClipboard(): $CancellablePromise<string> {
    return $Call.ByID(2339328967);
}

/**
 * SendPingToPhone pings the phone's listener at the captured peer address
 * using core.SendPing and the pair token. It returns a short RTT summary;
 * the RTT is also appended to the log. An update-required reply is logged
 * with the parseable prefix (verbatim canonical message) and returned as an
 * error so the UI can banner immediately; an auth rejection is logged and
 * returned with the peer kept. Any other (dial/network) failure clears the
 * ephemeral peer (the remembered device stays) and logs
 * "phone peer lost (<err>)" so IsPaired flips false on the next poll.
 * Fail closed while peer coordinates are unknown.
 */
export function SendPingToPhone(): $CancellablePromise<string> {
    return $Call.ByID(2215868813);
}

/**
 * SetClipboardMode stores a new clipboard direction (off, mac_to_phone,
 * phone_to_mac, two_way), persists it, and syncs immediately when paired
 * (else it rides the next heartbeat). Unknown modes fail closed.
 */
export function SetClipboardMode(mode: string): $CancellablePromise<string> {
    return $Call.ByID(1377316233, mode);
}

/**
 * SetCustomName stores the Mac-local rename alias shown instead of the
 * phone's advertised name. Empty clears the alias (falls back to the
 * advertised name). Over-long input fails closed without touching state.
 * The alias lives in device.json keyed to this phone; advertised facts keep
 * updating underneath so clearing reveals the current phone name.
 */
export function SetCustomName(name: string): $CancellablePromise<string> {
    return $Call.ByID(4188241244, name);
}

/**
 * SetNotificationsEnabled flips the notification master switch, persists,
 * and syncs when paired.
 */
export function SetNotificationsEnabled(enabled: boolean): $CancellablePromise<string> {
    return $Call.ByID(2764020233, enabled);
}

/**
 * StartClipboardWatcher watches the Mac pasteboard and pushes changes via
 * PushClipboard (mode-gated downstream). It returns a stop func; the caller
 * (main.go) owns lifecycle. Change-only: identical hashes never push, so an
 * idle Mac costs one local pbpaste per tick and nothing else.
 */
export function StartClipboardWatcher(): $CancellablePromise<context$0.CancelFunc> {
    return $Call.ByID(2972424142);
}
