// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service exposes pair state and phone-ping actions to the Wails frontend.
 * Pair fields are set once at startup by main.go; peer coordinates are
 * learned later from accepted phone pings (see WrapHandler) and remembered
 * on disk (see persist.go) so a restart still shows the last phone.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ForgetLastDevice drops the remembered phone: it clears the ephemeral
 * return path, the TOFU phone pin, and the persisted device.json so the UI
 * falls back to the pairing flow. Pair identity and token are untouched
 * (the QR keeps working). Fail closed when no phone was ever remembered;
 * a disk-delete failure still clears memory but returns the wrapped error.
 */
export function ForgetLastDevice(): $CancellablePromise<string> {
    return $Call.ByID(1960282719);
}

/**
 * GetFingerprint returns the hex SHA-256 of the server TLS cert (TOFU pin).
 */
export function GetFingerprint(): $CancellablePromise<string> {
    return $Call.ByID(1850633148);
}

/**
 * GetLastDevice returns the last phone this Mac paired with, even after the
 * ephemeral peer expired or the app restarted. Typed binding for the offline
 * "Last connected" card; HasDevice is false when no phone ever paired.
 * Battery fields are nil while unknown; DisplayName is the rename alias when
 * set, else the advertised name, else "" (the UI falls back to "Phone").
 */
export function GetLastDevice(): $CancellablePromise<$models.LastDeviceNotice> {
    return $Call.ByID(2294029394);
}

/**
 * GetLog returns recent core server log lines, oldest first.
 */
export function GetLog(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2517628202);
}

/**
 * GetPairJSON returns the EncodePairQR JSON shown as the pairing QR.
 */
export function GetPairJSON(): $CancellablePromise<string> {
    return $Call.ByID(1076374734);
}

/**
 * GetPeerAddr returns "host:port" learned from the phone's last accepted
 * ping, or "" while unknown or expired (past peerTTL). The frontend keeps
 * [Ping phone] disabled until this is non-empty.
 */
export function GetPeerAddr(): $CancellablePromise<string> {
    return $Call.ByID(1816887919);
}

/**
 * GetPeerDevice returns the live advertised facts while the phone is paired
 * (within peerTTL), or null-equivalent (HasDevice false) otherwise. Typed
 * binding so the sidebar header shows model + battery without scraping logs.
 */
export function GetPeerDevice(): $CancellablePromise<$models.LastDeviceNotice> {
    return $Call.ByID(3047827702);
}

/**
 * GetUpdateNotice returns the newest version-gate outcome, or inactive.
 * Typed binding: the frontend banners this verbatim, never parses GetLog.
 */
export function GetUpdateNotice(): $CancellablePromise<$models.UpdateNotice> {
    return $Call.ByID(2756057269);
}

/**
 * HeartbeatTick is the 20s auto-reconnect tick (mirrors the Android
 * heartbeat): when paired it refreshes presence with a ping; when expired it
 * redials the remembered phone. Failures only land in the log — never an
 * error return, never the update banner path beyond setUpdate.
 */
export function HeartbeatTick(): $CancellablePromise<void> {
    return $Call.ByID(3546295225);
}

/**
 * IsPaired reports whether an accepted phone ping taught us the return path
 * recently (within peerTTL). Typed binding: the frontend derives `paired`
 * from this, never from log text. It flips false peerTTL after the last
 * accepted ping, or immediately after a dial failure clears the peer.
 */
export function IsPaired(): $CancellablePromise<boolean> {
    return $Call.ByID(1285126505);
}

/**
 * ReconnectToLastDevice redials the remembered phone even after the
 * ephemeral peer expired or the app restarted. Success refreshes the peer
 * (IsPaired flips true); dial failures keep the remembered device so the UI
 * still shows "Last connected". Fail closed when no phone ever paired.
 */
export function ReconnectToLastDevice(): $CancellablePromise<string> {
    return $Call.ByID(1244154842);
}

/**
 * SendPingToPhone pings the phone's listener at the captured peer address
 * using core.SendPing and the pair token. It returns a short RTT summary;
 * the RTT is also appended to the log. An update-required reply is logged
 * with the parseable prefix (verbatim canonical message) and returned as an
 * error so the UI can banner immediately; an auth rejection is logged and
 * returned with the peer kept. Any other (dial/network) failure clears the
 * ephemeral peer (the remembered device stays) and logs
 * "phone peer lost (<err>)" so IsPaired flips false on the next poll.
 * Fail closed while peer coordinates are unknown.
 */
export function SendPingToPhone(): $CancellablePromise<string> {
    return $Call.ByID(2215868813);
}

/**
 * SetCustomName stores the Mac-local rename alias shown instead of the
 * phone's advertised name. Empty clears the alias (falls back to the
 * advertised name). Over-long input fails closed without touching state.
 * The alias lives in device.json keyed to this phone; advertised facts keep
 * updating underneath so clearing reveals the current phone name.
 */
export function SetCustomName(name: string): $CancellablePromise<string> {
    return $Call.ByID(4188241244, name);
}
